spring:
  ai:
    openai:
      api-key: hU_NYThcjoK8ibiVrPC1-Zr4v8CHpmjF4pzThA2S_RiRmYbTUFLHLPR67zHpUYIRytuQmwunU3H7n8A-m20Lsw
      base-url: https://infer-modelarts-cn-southwest-2.modelarts-infer.com/v1/infers/861b6827-e5ef-4fa6-90d2-5fd1b2975882
      chat:
        options:
          model: DeepSeek-R1
server:
  servlet:
    context-path: /api