spring:
  application:
    name: vben-api
  # DataSource Config
  datasource:
    url: jdbc:mysql://192.168.3.57:3306/app_vben
    username: root
    password: 123456
    type: com.zaxxer.hikari.HikariDataSource
  threads:
    virtual:
      enabled: false
  data:
    redis:
      host: 192.168.3.57
      port: 6379
      database: 0
      # 连接超时
      connect-timeout: 5s
      # 读超时
      timeout: 5s

      # Lettuce 客户端的配置
      lettuce:
        # 连接池配置
        pool:
          # 最小空闲连接
          min-idle: 0
          # 最大空闲连接
          max-idle: 10
          # 最大活跃连接
          max-active: 200
          # 从连接池获取连接 最大超时时间，小于等于0则表示不会超时
          max-wait: -1ms

server:
  port: 8080
  servlet:
    context-path: /api

mybatis-flex:
  mapper-locations: classpath*:/mappers/**/*.xml

sa-token:
  token-name: Authorization
  # token前缀
  token-prefix: Bearer
  jwt-secret-key: hafhwoirwoiu2o342ofsf979HSFHS3
  # 一天
  timeout: 86400
  # 不设置Cookie
  is-read-cookie: false
